# File: _config.yml
# Where things are
source:       .
destination:  ./_site
plugins_dir:  _plugins
layouts_dir:  _layouts
data_dir:     _data
includes_dir: _includes
collections:
  posts:
    output:   true

theme: jekyll-theme-architect



webrick:
  headers:
    My-Header: My-Value
    My-Other-Header: My-Other-Value
    
defaults:
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
