# File: _config.yml
theme: jekyll-theme-architect

webrick:
  headers:
    My-Header: My-Value
    My-Other-Header: My-Other-Value
    
defaults:
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
