--- 
"pages" : 
  # "permalink" : "/:_root/"
  # layout : 'custom-page-layout'
  
projects: 
  summary_lines: 5  # default is 20

design: 
  summary_lines: 5  # default is 20

my-collection: 
  use: 

theme-bootstrap-2:
  use: theme

  # _root:
  # summary_lines: 5
  # rss:
  #   enable: false
  # paginator:
  #   enable: true
  # font:
  # use: 'ignore'
